### PR TITLE
Apply WordPress coding standards

### PR DESCRIPTION
**Pull request by grandeljay**
# Fixes
* End of line character is invalid; expected "\n" but found "\r\n"
* File must end with a newline character
* Parenthesis should always be used when instantiating a new object.
* Short array syntax is not allowed
* Parenthesis should always be used when instantiating a new object.
* Equals sign not aligned with surrounding assignments; expected X spaces but found Y spaces
* A gettext call containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the placeholders.
* Using short ternaries is not allowed
* Opening parenthesis of a multi-line function call must be the last content on the line
* Closing parenthesis of a multi-line function call must be on a line by itself
* Missing space before array opener.
* Missing space after array opener.
* Use Yoda Condition checks, you must.
* Array keys must be surrounded by spaces unless they contain a string or an integer.
* Only one argument is allowed per line in a multi-line function call
* Inline PHP statement must end with a semicolon
* Array keys must NOT be surrounded by spaces if they only contain a string or an integer.
* Overriding WordPress globals is prohibited. Found assignment to $id
* Expected 1 spaces before closing parenthesis; 0 found
* Expected 1 space(s) after closing parenthesis; found 0
* Expected 1 space(s) after FOREACH keyword; 0 found
* Expected 1 space after "!"; 0 found
* Short PHP opening tag used with echo; expected "<?php echo $this ..." but found "<?= $this ..."
  (partially, that's why I have also listed it below again)
* String "</script>" does not require double quotes; use single quotes instead
* Tabs must be used to indent lines; spaces are not allowed
* The CASE body must start on the line following the statement
* Variable "$metaData" is not in valid snake_case format, try "$meta_data"
* Variable "$imageSource" is not in valid snake_case format, try "$image_source"
* Object property "$thumbnailSize" is not in valid snake_case format, try "$thumbnail_size"
* Variable "$attachmentId" is not in valid snake_case format, try "$attachment_id"

# Remaining issues (to do)
These issues are not necessarily easy to fix for an outsider, I recommend you have a look at them. I would also be willing to fix them myself if you let me know how you would like to handle them.

* Filenames should be all lowercase with hyphens as word separators. Expected filename.php, but found Filename.php.
* Class file names should be based on the class name with "class-" prepended. Expected class-filename.php, but found Filename.php.
* All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$code'.
* Detected high pagination limit, `posts_per_page` is set to `2000`
* Found: ==. Use strict comparisons (=== or !==).
* parse_url() is discouraged because of inconsistency in the output across PHP versions; use wp_parse_url() instead.
* date() is affected by runtime timezone changes which can cause date/time to be incorrectly displayed. Use gmdate() instead.
* Short PHP opening tag used with echo; expected "<?php echo esc_html ..." but found "<?= esc_html ..."
* Resource version not set in call to wp_enqueue_style(). This means new versions of the style will not always be loaded due to browser caching.
* json_encode() is discouraged. Use wp_json_encode() instead.
* Visibility must be declared on method "generate"
* Not using strict comparison for in_array; supply true for third argument.
* Overriding WordPress globals is prohibited. Found assignment to $shortcode_tags

### CODE REVIEW

**Comment by rilwis** [comment]
Hi @grandeljay ,

Thanks for your help. However, we don't strictly follow all WordPress coding standards. These are things we will ignore:

- Parenthesis should always be used when instantiating a new object. We prefer no parenthesis, which is cleaner.
- Short array syntax is not allowed. We prefer short array syntax, which is much cleaner.
- Equals sign not aligned with surrounding assignments. It's optional, not strict.
- Using short ternaries is not allowed. We prefer using it to make the statement short.
- Opening/closing parenthesis of a multi-line function call must be the last content on the line. It's optional. Keeping them in the same line is fine. Sometimes, it makes the code cleaner (similar to what we used to do with jQuery).
- Use Yoda Condition checks, you must. This is optional, not strict.

And many other rules. The main goal here is to keep the code short and clean.

**Comment by grandeljay** [comment]
Do you have a custom ruleset (i. e. for phpcs) to help you follow these rules? I would be interested in something like this since I am not familiar with this your custom style

**Comment by rilwis** [comment]
I'll prepare an xml file and setup phpcs to check this.

**Comment by rilwis** [comment]
I've added a new branch https://github.com/elightup/slim-seo/tree/feature/coding-standards, which has rules for PHPCS.

To check/fix, please run this commands:

```
phpcs --standard="phpcs.xml" .
phpcbf --standard="phpcs.xml" .
```

**Comment by grandeljay** [comment]
Sweet! Thanks!

Unfortunately [I seem to be having issues with it](https://github.com/ikappas/vscode-phpcs/issues/195) (using VS Code), hope to get it all sorted.

**Comment by grandeljay** [comment]
Nvm, I noticed that extension is way outdated. I am using a more up-to-date one now and it works 🥳

**Pull request closed without merging**
